#!/bin/sh
### BEGIN INIT INFO
# Provides:           dynaswap-useradd
# Required-Start:     $syslog $remote_fs
# Required-Stop:      $syslog $remote_fs
# Should-Start:       cgroupfs-mount cgroup-lite
# Should-Stop:        cgroupfs-mount cgroup-lite
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  adding users and updating current ssh keys.
# Description:		  adding users and updating current ssh keys.
#
### END INIT INFO


#Adding Users to Unix
sudo useradd -d /home/phillity -s /bin/bash -m phillity> /dev/null
	if [ $? -ne 0 ]
		then
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnfvQqMaVN2TX/aDA/GUbhZoLBLWh7CSmXdKPeHKbB/P5FCqsY6WD/QVZTC6I5Oq9nqYHb7lUmQQo7S/Q+jZSccG2IWr+1Zr+sFYRGf625lL0vBKfomx+d5fr85tOEj1VsaLhQnyx6dv/VkD/1t8Fmo9Np/0EVqCl70//VVFOfkpPIMbqrcbJPQUCBhSb+lTPzdo1iGqEnjoF7x9S1TWlxWXPicXlRpBLbd6pT3Pa/QdP54YID6pC7Im7z5BywtcT1VTpHH+Yw058NTenY55C3k+a+DBbyzT8RZwKWgcd6SvoZebo8SeBpCr5WiMQxfJWmYMrtqjJhzMDJurhX9/vsQ== rsa-key-20190119'>/home/phillity/.ssh/authorized_keys
	else
		sudo mkdir -p /home/phillity/.ssh/
		sudo chmod 700 /home/phillity/.ssh/
		sudo chown phillity:phillity /home/phillity/.ssh
		sudo touch /home/phillity/.ssh/authorized_keys
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnfvQqMaVN2TX/aDA/GUbhZoLBLWh7CSmXdKPeHKbB/P5FCqsY6WD/QVZTC6I5Oq9nqYHb7lUmQQo7S/Q+jZSccG2IWr+1Zr+sFYRGf625lL0vBKfomx+d5fr85tOEj1VsaLhQnyx6dv/VkD/1t8Fmo9Np/0EVqCl70//VVFOfkpPIMbqrcbJPQUCBhSb+lTPzdo1iGqEnjoF7x9S1TWlxWXPicXlRpBLbd6pT3Pa/QdP54YID6pC7Im7z5BywtcT1VTpHH+Yw058NTenY55C3k+a+DBbyzT8RZwKWgcd6SvoZebo8SeBpCr5WiMQxfJWmYMrtqjJhzMDJurhX9/vsQ== rsa-key-20190119'>/home/phillity/.ssh/authorized_keys
		sudo chown phillity:phillity /home/phillity/.ssh/authorized_keys
		sudo usermod -aG users phillity
		sudo usermod -aG sudo phillity
	fi

sudo useradd -d /home/saptpurk -s /bin/bash -m saptpurk> /dev/null
	if [ $? -ne 0 ]
		then
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsE0rVS6zjGteLDOfAwRxZC4MAG5StjqJRwAb5Ydkdq7tY/rv5PWeoOAO2khisjt+Vo1Ds7TZLMU7uk/pEZfAxmkvXC0R8MrgWWZ2GisRvY+4/HCZh1bcCqDJLY7i9doyPvXmNd0QwCwQs4nEuGIt+KguMgRYD5KxUfeJCzlWQ5bRb2Y9LZ/7FpId4WpRrvsqnDEF2MRRNA26kdL+L8ZQNtKwhbgK4AgwOtiXbAATqHsnrUY21w7aWCIVIr4ZPxisYYnX1+amPeRnd5JLxPyuCZBKvPvgUZaSfe+fJ6w0x91mBzKWag8wpqi61Sg1tcsNm2QCC4N/dOwf+5WwFJrdMw== saptpurk-sunbiz' >/home/saptpurk/.ssh/authorized_keys
	else
		sudo mkdir -p /home/saptpurk/.ssh/
		sudo chmod 700 /home/saptpurk/.ssh/
		sudo chown saptpurk:saptpurk /home/saptpurk/.ssh
		sudo touch /home/saptpurk/.ssh/authorized_keys
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsE0rVS6zjGteLDOfAwRxZC4MAG5StjqJRwAb5Ydkdq7tY/rv5PWeoOAO2khisjt+Vo1Ds7TZLMU7uk/pEZfAxmkvXC0R8MrgWWZ2GisRvY+4/HCZh1bcCqDJLY7i9doyPvXmNd0QwCwQs4nEuGIt+KguMgRYD5KxUfeJCzlWQ5bRb2Y9LZ/7FpId4WpRrvsqnDEF2MRRNA26kdL+L8ZQNtKwhbgK4AgwOtiXbAATqHsnrUY21w7aWCIVIr4ZPxisYYnX1+amPeRnd5JLxPyuCZBKvPvgUZaSfe+fJ6w0x91mBzKWag8wpqi61Sg1tcsNm2QCC4N/dOwf+5WwFJrdMw== saptpurk-sunbiz' >/home/saptpurk/.ssh/authorized_keys
		sudo chown saptpurk:saptpurk /home/saptpurk/.ssh/authorized_keys
		sudo usermod -aG users saptpurk
		sudo usermod -aG sudo saptpurk
	fi

sudo useradd -d /home/johliu -s /bin/bash -m johliu> /dev/null
	if [ $? -ne 0 ]
		then
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAx2Bul5MGeu1i/j9ST4utCeDIpyTsV1lRO+Po/vz2Lp7lFaiL4BJX43IAwS8UxLpgg9GanM/guNS+xGZ40pZO0cEP9sFGuf3emp9NgKvTCHvHJJZEImmtQWky7blqjov2w3cNfXESbCUVygBw5t7y636wOLokJnrCqSXcmSdZJl40f+KrQMmFWRnnNmyiwdec7E/GNvzvmraz3/CXXYWuYAYPG71SuOr3ny+gNfQMIXr+yegKeai+hrnXTX3n5Y9tX0OzYSPqRTy0gjQycbsnMq87djr+jvKlWxRvAFD3qQKCP8gFJVv249xdXMzyzgfzBTKRSelzY9ZABkZN8cIYRQ== rsa-key-20190211'>/home/johliu/.ssh/authorized_keys
	else
		sudo mkdir -p /home/johliu/.ssh/
		sudo chmod 700 /home/johliu/.ssh/
		sudo chown johliu:johliu /home/johliu/.ssh
		sudo touch /home/johliu/.ssh/authorized_keys
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAx2Bul5MGeu1i/j9ST4utCeDIpyTsV1lRO+Po/vz2Lp7lFaiL4BJX43IAwS8UxLpgg9GanM/guNS+xGZ40pZO0cEP9sFGuf3emp9NgKvTCHvHJJZEImmtQWky7blqjov2w3cNfXESbCUVygBw5t7y636wOLokJnrCqSXcmSdZJl40f+KrQMmFWRnnNmyiwdec7E/GNvzvmraz3/CXXYWuYAYPG71SuOr3ny+gNfQMIXr+yegKeai+hrnXTX3n5Y9tX0OzYSPqRTy0gjQycbsnMq87djr+jvKlWxRvAFD3qQKCP8gFJVv249xdXMzyzgfzBTKRSelzY9ZABkZN8cIYRQ== rsa-key-20190211'>/home/johliu/.ssh/authorized_keys
		sudo chown johliu:johliu /home/johliu/.ssh/authorized_keys
		sudo usermod -aG users johliu
		sudo usermod -aG sudo johliu
	fi

sudo useradd -d /home/xyu1 -s /bin/bash -m xyu1> /dev/null
	if [ $? -ne 0 ]
		then
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAylB3zSmCaO+cB8vcGhgSbquvrrNS2buj3Jq/jDzWskJBjAD3JG6QMlCm54dzXa26KqqEy4d/k8rXk20wU6SNwVJkgoRissq3kGvQkgXkGQbhEROu3I1/tlg+h5nB3yHMm6hMXPHzVLRr3IX3V1SQI58gSeNEe571K8CXkOkguSdxgGGZITc8WLyoxaXN7sRVQ5hNsPrffdYjXFJqsbyhkS4VaNnWKHubP2FNVhof2Qe24lcdFzuu01ZlrVOxDmZtWuekMHrnDcm+8S/gQmONUdqq//Z4rrLTCi5bmc80WRWtdRE5fGdhS0C4ew0hsvwK33hiPZcBV3n35xc8XymbQw== rsa-key-20190516'>/home/xyu1/.ssh/authorized_keys
	else
		sudo mkdir -p /home/xyu1/.ssh/
		sudo chmod 700 /home/xyu1/.ssh/
		sudo chown xyu1:xyu1 /home/xyu1/.ssh
		sudo touch /home/xyu1/.ssh/authorized_keys
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAylB3zSmCaO+cB8vcGhgSbquvrrNS2buj3Jq/jDzWskJBjAD3JG6QMlCm54dzXa26KqqEy4d/k8rXk20wU6SNwVJkgoRissq3kGvQkgXkGQbhEROu3I1/tlg+h5nB3yHMm6hMXPHzVLRr3IX3V1SQI58gSeNEe571K8CXkOkguSdxgGGZITc8WLyoxaXN7sRVQ5hNsPrffdYjXFJqsbyhkS4VaNnWKHubP2FNVhof2Qe24lcdFzuu01ZlrVOxDmZtWuekMHrnDcm+8S/gQmONUdqq//Z4rrLTCi5bmc80WRWtdRE5fGdhS0C4ew0hsvwK33hiPZcBV3n35xc8XymbQw== rsa-key-20190516'>/home/xyu1/.ssh/authorized_keys
		sudo chown xyu1:xyu1 /home/xyu1/.ssh/authorized_keys
		sudo usermod -aG users xyu1
		sudo usermod -aG sudo xyu1
	fi

sudo useradd -d /home/bhaakens -s /bin/bash -m bhaakens> /dev/null
	if [ $? -ne 0 ]
		then
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA61ks0mrBYWkVKMWFSfkyIy/qqd3iBlJ2ezvss/LXUL70537ct7hAS/BWQ/Cn18Lrv2dmmEvOgWxzzgvqL/YFz32yEKGeYoVEuummTOwnSQc9lxwM+aZVf9XHDEFfJdKR2Q0LWnzUUxAAMVtTfDdPnAOpEf+2Pnx9puw4OtEBhB3zgBpvVQS0/PvjIEwEzk+lQa91lnebS2c8lmQuHAfvZm0Ml7SKIyovKkvqPwmIv5Ns4q79CoQ9a8zHrvDkmoAo2rXNnw7kQyO/0hBiNNajxpXhJ2iRjjwp0n6gJqMrZbmo73Bj6rrUyrIO9BRZfeFIzH7NWABuABcdoaSN90p+Ew== rsa-key-20190516'>/home/bhaakens/.ssh/authorized_keys
	else
		sudo mkdir -p /home/bhaakens/.ssh/
		sudo chmod 700 /home/bhaakens/.ssh/
		sudo chown bhaakens:bhaakens /home/bhaakens/.ssh
		sudo touch /home/bhaakens/.ssh/authorized_keys
		sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA61ks0mrBYWkVKMWFSfkyIy/qqd3iBlJ2ezvss/LXUL70537ct7hAS/BWQ/Cn18Lrv2dmmEvOgWxzzgvqL/YFz32yEKGeYoVEuummTOwnSQc9lxwM+aZVf9XHDEFfJdKR2Q0LWnzUUxAAMVtTfDdPnAOpEf+2Pnx9puw4OtEBhB3zgBpvVQS0/PvjIEwEzk+lQa91lnebS2c8lmQuHAfvZm0Ml7SKIyovKkvqPwmIv5Ns4q79CoQ9a8zHrvDkmoAo2rXNnw7kQyO/0hBiNNajxpXhJ2iRjjwp0n6gJqMrZbmo73Bj6rrUyrIO9BRZfeFIzH7NWABuABcdoaSN90p+Ew== rsa-key-20190516'>/home/bhaakens/.ssh/authorized_keys
		sudo chown bhaakens:bhaakens /home/bhaakens/.ssh/authorized_keys
		sudo usermod -aG users bhaakens
		sudo usermod -aG sudo bhaakens
	fi
	
case $1 in
start)
        ;;
stop)
        ;;
restart)
        ;;
esac
exit 0
